#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RaysHotDogs.Resource", IsApplication=true)]

namespace RaysHotDogs
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int FavoritesIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int MeatLoversIcon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int RayLogo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int VeggieLoversIcon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int MyButton = 2131034125;
			
			// aapt resource value: 0x7f050012
			public const int aboutButton = 2131034130;
			
			// aapt resource value: 0x7f05000a
			public const int amountEditText = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int callTextView = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int cancelButton = 2131034121;
			
			// aapt resource value: 0x7f05000f
			public const int cartButton = 2131034127;
			
			// aapt resource value: 0x7f050007
			public const int descriptionTextView = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int fragmentContainer = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int hotDogImageView = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int hotDogListView = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int hotDogNameTextView = 2131034117;
			
			// aapt resource value: 0x7f05000e
			public const int logoImageView = 2131034126;
			
			// aapt resource value: 0x7f050003
			public const int mainScrollView = 2131034115;
			
			// aapt resource value: 0x7f050011
			public const int mapButton = 2131034129;
			
			// aapt resource value: 0x7f05000b
			public const int orderButton = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int phoneNumberTextView = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int priceTextView = 2131034120;
			
			// aapt resource value: 0x7f050014
			public const int rayPictureImageView = 2131034132;
			
			// aapt resource value: 0x7f050006
			public const int shortDescriptionTextView = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int takePictureButton = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int textView1 = 2131034131;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FavoriteHotDogFragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HotDogDetailView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int HotDogMenuView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int HotDogRowView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MainMenu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MeatLoversFragment = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TakePictureView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int VeggieLoversFragment = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
